### ISSUE TITLE
.indexOf('WARNING: Method TypeError

### ISSUE THREAD

**Issue by kokororin** [giakki/uncss#125]
Excuse me. How does this error occur?

 ```
[moekami@oyasumi ~]$ uncss http://tieba.oyasumi.moe/forum.html > test.css

/usr/lib/node_modules/uncss/lib/lib.js:26
        var isNot192OSXError = (err || stderr || '').indexOf('WARNING: Method 
                                                     ^
TypeError: Object Error: stdout maxBuffer exceeded. has no method 'indexOf'
    at /usr/lib/node_modules/uncss/lib/lib.js:26:54
    at ChildProcess.exithandler (child_process.js:644:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)

```

Thank you!

**Comment by XhmikosR** [comment]
@kokororin: bump for feedback ^^
