### ISSUE TITLE
select: Invalid argument

### ISSUE THREAD

**Issue by corysimmons** [giakki/uncss#171]
I'm trying to use a lot of pages (hundreds) within `sitemaps.json` as a simple array (so `["http:\/\/dev.foo.org\/cats\/kittens\/","http:\/\/dev.foo.org\/dogs\/puppies\/",...]`).

This works when it's only a handful of documents, but when I have hundreds of documents it throws hundreds of `select: Invalid argument` errors, followed by some PhantomJS fail (not specified).

```
...
select: Invalid argument
select: Invalid argument
select: Invalid argument
select: Invalid argument
select: Invalid argument
select: Invalid argument
select: Invalid argument
select: Invalid argument
phantomjs(35781,0x11f2ab000) malloc: *** error for object 0x1049b6f60: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
select: Invalid argument
select: Invalid argument
select: Invalid argument
select: Invalid argument
select: Invalid argument
select: Invalid argument
select: Invalid argument
select: Invalid argument
select: Invalid argument

/Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                                 ^
Error: Cannot load http://dev.foo.org/cats/kittens/: Phantomjs returned status fail
    at reject (/Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/lib/phantom/start.js:71)
    at onPageLoaded (:4)
    at :/modules/webpage.js:281
    -----------------------------------------------------------------------
    at Phantom._send (/Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/lib/Phantom.js:165:20)
    at Page.run (/Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/lib/Page.js:62:25)
    at Phantom.openPage (/Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/lib/Phantom.js:123:17)
    at Object.fromRemote (/Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/src/phantom.js:148:20)
    at /Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/src/uncss.js:41:28
    at tryCatcher (/Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/util.js:24:31)
    at MappingPromiseArray._promiseFulfilled (/Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/map.js:54:38)
    at MappingPromiseArray.init [as _init$] (/Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/promise_array.js:92:18)
    at MappingPromiseArray.init (/Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/map.js:27:23)
    at Async._drainQueue (/Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/async.js:182:12)
    at Async._drainQueues (/Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/async.js:187:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/cory/Desktop/vip-quickstart/www/wp-content/themes/vip/foo-responsive/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

Not sure if this is an UnCSS or PhantomJS issue. I'd appreciate any ideas, or just pointing me in the right direction.

**Comment by murgatroydj** [comment]
did you ever solve this issue?

**Comment by corysimmons** [comment]
Nope.

If I ever find time I'll write my own uncss'er. The current selection isn't very good.

**Comment by replete** [comment]
@corysimmons Out of interest, given that you seem to have advanced use of UnCSS, how do you approach the problem of dynamic styles and related selectors?

I haven't used UnCSS in production because there is no easy way to find related styles (e.g. related `:hover`, `>`, selectors etc .

**Comment by corysimmons** [comment]
> I want to solve this problem, but don't have the time between commercial applications :(

me_irl

**Comment by RyanZim** [comment]
@corysimmons When used as a postcss plugin, uncss serializes the requests to PhantomJS. (PhantomJS doesn't seem to enjoy running multiple instances side by side) Could you try using the postcss plugin and see if that resolves this?

**Comment by mikelambert** [comment]
I've just created a pull request https://github.com/giakki/uncss/pull/249 that should fix the serialization issues. @corysimmons, if you're still investigating this issue, you could alternately try that tree (https://github.com/mikelambert/uncss/tree/serialized) from your gulp-uncss dependency to see if it helps your issue.

**Comment by corysimmons** [comment]
Sorry, I don't have access to that code anymore to test this out on. I'll try to test it out on future projects. Thanks for your work on this.

**Comment by RyanZim** [comment]
Uncss 0.15.0 no longer uses PhantomJS, so this should be fixed.
