### ISSUE TITLE
e.g command at readme.md error

### ISSUE THREAD

**Issue by GreanMaster** [giakki/uncss#175]
when I use this command `uncss http://getbootstrap.com/examples/jumbotron/ > unuse.css`  

I got this alien lang 
```
C:\Users\Jame\AppData\Roaming\npm\node_modules\uncss\node_modules\bluebird\js\main\async.js:43
        fn = function () { throw arg; };
                                 ^
Error: uncss/node_modules/css: unable to parse http://getbootstrap.com/dist/css/bootstrap.min.css :
missing '}' near line 2:277
        1:        /*** uncss> filename: http://getbootstrap.com/dist/css/bootstrap.min.css ***/
        2:     -> ๏ฟฝ#๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝS๏ฟฝ๏ฟฝ↓๏ฟฝ♣M๓—♥,๏ฟฝ]∟๏ฟฝV๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝะWO๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝZ๏ฟฝ{๏ฟฝ
        3:        ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ3๏ฟฝ'๏ฟฝ#kวฃ๏ฟฝ๏ฟฝ♣๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝa๏ฟฝv0↑๏ฟฝG๏ฟฝ๏ฟฝo๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ▲D๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ

KE-4๏ฟฝ๏ฟฝ๏ฟฝO๏ฟฝ๏ฟฝ๏ฟฝP§๏ฟฝ๏ฟฝ๏ฟฝ_๏ฟฝ๏ฟฝูฒ๏ฟฝlw0S๏ฟฝ⌂๏ฟฝ↔WsT๏ฟฝ๏ฟฝI
        5:        ๏ฟฝ๏ฟฝ๏ฟฝีผสฆ๏ฟฝl๏ฟฝ ;0๏ฟฝ\๏ฟฝ♫L๏ฟฝฬ♥๏ฟฝH๏ฟฝ๏ฟฝ◄๏ฟฝ-๏ฟฝ`๏ฟฝ0๏ฟฝP๏ฟฝ๏ฟฝ'h๏ฟฝ)∟
        6:        ☺๏ฟฝqW}๏ฟฝร–๏ฟฝ▬#๏ฟฝัt๏ฟฝ๏ฟฝ↑๏ฟฝ
```

OS: windows 8.1

Thank :)

**Comment by XhmikosR** [comment]
Works perfectly fine here


```
C:\Users\xmr\Desktop\uncss>node -v && npm -v
v0.12.5
2.11.2

C:\Users\xmr\Desktop\uncss>node bin\uncss http://getbootstrap.com/examples/jumbo
tron/ > unuse.css
```

**Comment by GreanMaster** [comment]
still don't work for me :cry:
```
λ node -v && npm -v
v0.12.5
2.12.0
```

```
λ uncss http://getbootstrap.com/examples/jumbotron/ > unuse.css
C:\Users\Jame\AppData\Roaming\npm\node_modules\uncss\node_modules\bluebird\js\main\async.js:43
        fn = function () { throw arg; };
                                 ^
Error: uncss/node_modules/css: unable to parse http://getbootstrap.com/dist/css/bootstrap.min.css :
missing '}' near line 2:166
        1:        /*** uncss> filename: http://getbootstrap.com/dist/css/bootstrap.min.css ***/
๏ฟฝ๏ฟฝ▲๏ฟฝฯธ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝำฉ<t;⌂๏ฟฝ๏ฟฝ๏ฟ๏ฟฝ?๏ฟฝ๏ฟฝr{,↓
        3:        ☼/๏ฟฝ3 q๏ฟฝ?๏ฟฝw๏ฟฝ5↕gz(a→`L๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ☼๏ฟฝ4๏ฟฝ~ฺฒS๏ฟฝ-๏ฟฝv๏ฟฝi๏ฟฝ?♠
        4:        ึง☼๏ฟฝ~๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ,๏ฟฝ๏ฟฝy9u๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ◄▬๏ฟฝ~๏ฟฝ๏ฟฝ๏ฟฝ?pg๏ฟฝ๏ฟฝ๏ฟฝ.
```

```
λ node %appdata%\npm\node_modules\uncss\bin http://getbootstrap.com/examples/jumbotron/ > unuse.css
module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Users\Jame\AppData\Roaming\npm\node_modules\uncss\bin'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

```
λ node %appdata%\npm\node_modules\uncss\bin\uncss http://getbootstrap.com/examples/jumbotron/ > unuse.css
C:\Users\Jame\AppData\Roaming\npm\node_modules\uncss\node_modules\bluebird\js\main\async.js:43
        fn = function () { throw arg; };
                                 ^
Error: uncss/node_modules/css: unable to parse http://getbootstrap.com/dist/css/bootstrap.min.css :
missing '}' near line 2:166
        1:        /*** uncss> filename: http://getbootstrap.com/dist/css/bootstrap.min.css ***/
๏ฟฝ๏ฟฝ▲๏ฟฝฯธ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝำฉ<t;⌂๏ฟฝ๏ฟฝ๏ฟ๏ฟฝ?๏ฟฝ๏ฟฝr{,↓
        3:        ☼/๏ฟฝ3 q๏ฟฝ?๏ฟฝw๏ฟฝ5↕gz(a→`L๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ☼๏ฟฝ4๏ฟฝ~ฺฒS๏ฟฝ-๏ฟฝv๏ฟฝi๏ฟฝ?♠
        4:        ึง☼๏ฟฝ~๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ,๏ฟฝ๏ฟฝy9u๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ๏ฟฝ◄▬๏ฟฝ~๏ฟฝ๏ฟฝ๏ฟฝ?pg๏ฟฝ๏ฟฝ๏ฟฝ.
```

I do something wrong ?

**Comment by XhmikosR** [comment]
No idea to be honest. Are you able to access that link via the browser?

Maybe @giakki has a better idea.

**Comment by GreanMaster** [comment]
yes I can access that link perfectly every browsers in my computer (chrome, firefox, ie11)

and I can ` uncss https://github.com/giakki/uncss/issues/175 > unuse.css` works perfectly.
