### ISSUE TITLE
JS error: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by Thomasdezeeuw** [giakki/uncss#201]
Issue moved from: https://github.com/ben-eb/gulp-uncss/issues/40. 

Running the following code with version 1.0.4 of gulp-uncss, 0.12.1 of uncss and 3.9.0 of Gulp.

```js
var gulp = require('gulp')
	, uncss = require('gulp-uncss')

	gulp.src(paths.src.style)
		.pipe(concat('style.css'))
		.pipe(uncss({
			html: ['./public/**/*.html']
		}))
		.pipe(gulp.dest(paths.dst.style))
```

Stacktrace:

```
/Users/thomas/Dropbox/dev/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^
TypeError: Cannot read property 'map' of undefined
    at getHTML (/Users/thomas/Dropbox/dev/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/src/uncss.js:28:28)
    at /Users/thomas/Dropbox/dev/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/src/uncss.js:221:20
    at /Users/thomas/Dropbox/dev/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/using.js:165:30
    at tryCatcher (/Users/thomas/Dropbox/dev/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/thomas/Dropbox/dev/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/Users/thomas/Dropbox/dev/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/Users/thomas/Dropbox/dev/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/Users/thomas/Dropbox/dev/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/thomas/Dropbox/dev/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/thomas/Dropbox/dev/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
```

**Comment by RyanZim** [comment]
@Thomasdezeeuw Is this still an issue for you?

**Comment by Thomasdezeeuw** [comment]
Yes I still got the same error, another stack trace:

```
/Users/thomas/Dropbox/dev/websites/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/release/async.js:48
        fn = function () { throw arg; };
                           ^
TypeError: Cannot read property 'map' of undefined
    at getHTML (/Users/thomas/Dropbox/dev/websites/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/src/uncss.js:28:28)
    at /Users/thomas/Dropbox/dev/websites/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/src/uncss.js:221:20
    at tryCatcher (/Users/thomas/Dropbox/dev/websites/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/release/util.js:11:23)
    at /Users/thomas/Dropbox/dev/websites/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/release/using.js:184:26
    at tryCatcher (/Users/thomas/Dropbox/dev/websites/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/Users/thomas/Dropbox/dev/websites/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/release/promise.js:491:31)
    at Promise._settlePromise (/Users/thomas/Dropbox/dev/websites/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/release/promise.js:548:18)
    at Promise._settlePromise0 (/Users/thomas/Dropbox/dev/websites/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/release/promise.js:593:10)
    at Promise._settlePromises (/Users/thomas/Dropbox/dev/websites/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/release/promise.js:676:18)
    at Promise._fulfill (/Users/thomas/Dropbox/dev/websites/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/release/promise.js:617:18)
    at PromiseArray._resolve (/Users/thomas/Dropbox/dev/websites/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/Users/thomas/Dropbox/dev/websites/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/Users/thomas/Dropbox/dev/websites/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/release/promise.js:553:26)
    at Promise._settlePromise0 (/Users/thomas/Dropbox/dev/websites/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/release/promise.js:593:10)
    at Promise._settlePromises (/Users/thomas/Dropbox/dev/websites/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/release/promise.js:676:18)
    at Async._drainQueue (/Users/thomas/Dropbox/dev/websites/thomasdezeeuw.nl/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/release/async.js:125:16)
```

**Comment by RyanZim** [comment]
I'm away from my dev machine right now; is this reproducible with vanilla UnCSS (eg. using the CLI)? The command would be something like:
```
uncss index.html -s '*.css' > bundle.css
```

**Comment by Thomasdezeeuw** [comment]
Can't reproduce this with the CLI. Power I did a little bit of digging, it seemed `uncss` was called with `undefined` as `files` paramater (`uncss(undefined, options, callback)`). Because there is no check against it was passed to `getHTML` which called `map` on it, assuming it's an array. Because you can't call `map` on `undefined` it crashes with this cryptic message.

Maybe the function can use some sanity checking of the passes paramaters. But this issue can be closed.

**Comment by RyanZim** [comment]
OK, thanks. I'll look into adding a sanity check.
