### ISSUE TITLE
Can't parse -webkit-keyframes

### ISSUE THREAD

**Issue by andre487** [giakki/uncss#203]
I got this error with my CSS file:
```
/Users/andre487/node_modules/uncss/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                                 ^
Error: uncss/node_modules/css: unable to parse http://local.yandex.ru:3333/static/web4/pages-desktop/search/_search.without-header.less.css :
@keyframes missing '{' near line 633:34
	628:        .spin2_progress_yes
	629:        {
	630:            position: relative;
	631:        }
	632:
	633:     -> @-webkit-keyframes islands-spin_ /*1*/
	634:        {
	635:            from
	636:            {
	637:                -webkit-transform: rotate(1deg);
	638:            }

    at error (/Users/andre487/node_modules/uncss/node_modules/css/node_modules/css-parse/index.js:57:15)
    at atkeyframes (/Users/andre487/node_modules/uncss/node_modules/css/node_modules/css-parse/index.js:267:25)
    at atrule (/Users/andre487/node_modules/uncss/node_modules/css/node_modules/css-parse/index.js:456:12)
    at rules (/Users/andre487/node_modules/uncss/node_modules/css/node_modules/css-parse/index.js:103:44)
    at stylesheet (/Users/andre487/node_modules/uncss/node_modules/css/node_modules/css-parse/index.js:73:16)
    at Object.module.exports [as parse] (/Users/andre487/node_modules/uncss/node_modules/css/node_modules/css-parse/index.js:485:10)
    at process (/Users/andre487/node_modules/uncss/src/uncss.js:158:22)
    at tryCatcher (/Users/andre487/node_modules/uncss/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Users/andre487/node_modules/uncss/node_modules/bluebird/js/main/promise.js:501:31)
    at Promise._settlePromiseAt (/Users/andre487/node_modules/uncss/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/Users/andre487/node_modules/uncss/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/Users/andre487/node_modules/uncss/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Users/andre487/node_modules/uncss/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/andre487/node_modules/uncss/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

**Comment by mikelambert** [comment]
We have switched to using postcss for all processing, instead of css/css-parse. Postcss is much more robust, and should be able to handle this CSS. Feel free to try again with the github master and see if it fixes your issue.

**Comment by RyanZim** [comment]
@mikelambert Any reason to keep this open?
