### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by lorvent** [giakki/uncss#238]
When running using gulp, i am getting following error

```
node_modules\bluebird\js\release\async.js:48
        fn = function () { throw arg; };
                           ^
Error: Cannot communicate with PhantomJS process: Unknown reason
    at Phantom._afterExit (D:\xampp\htdocs\globals\node_modules\phridge\lib\Phantom.js:353:17)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

any help would be great,
thanks.

**Comment by RyanZim** [comment]
@lorvent Have you tried deleting `node_modules`, running `npm cache clean`, followed by `npm i`?

**Comment by lorvent** [comment]
i think that fixed the problem
