### ISSUE TITLE
Error: uncss/node_modules/css: unable to parse undefined: property missing ':' near line 1:36

### ISSUE THREAD

**Issue by nundel** [giakki/uncss#247]
Hi! 
I'm trying to run gulp-uncss and getting same error: 
```
 uncss/node_modules/css: unable to parse undefined:
property missing ':' near line 1:36
 1:     -> @media print{@page{#DocumentViewDIV{
        2:          50%,
        3:          100%{-webkit-transform:translateY(0);transform:translateY(0)}25%,
        4:          75%{-webkit-transform:translateY(-6px);transform:translateY(-6px)}}@keyframes hvr-icon-up{0%,
        5:          50%,
        6:          100%{-webkit-transform:translateY(0);transform:translateY(0)}25%,

    at error (C:\wamp64\www\css-cleanup\node_modules\uncss\node_modules\css\node_modules\css-parse\index.js:57:15)
    at declaration (C:\wamp64\www\css-cleanup\node_modules\uncss\node_modules\css\node_modules\css-parse\index.js:189:33)
    at atpage (C:\wamp64\www\css-cleanup\node_modules\uncss\node_modules\css\node_modules\css-parse\index.js:372:19)
    at atrule (C:\wamp64\www\css-cleanup\node_modules\uncss\node_modules\css\node_modules\css-parse\index.js:463:10)
    at rules (C:\wamp64\www\css-cleanup\node_modules\uncss\node_modules\css\node_modules\css-parse\index.js:103:44)
    at atmedia (C:\wamp64\www\css-cleanup\node_modules\uncss\node_modules\css\node_modules\css-parse\index.js:345:35)
    at atrule (C:\wamp64\www\css-cleanup\node_modules\uncss\node_modules\css\node_modules\css-parse\index.js:457:10)
    at rules (C:\wamp64\www\css-cleanup\node_modules\uncss\node_modules\css\node_modules\css-parse\index.js:103:44)
    at stylesheet (C:\wamp64\www\css-cleanup\node_modules\uncss\node_modules\css\node_modules\css-parse\index.js:73:16)
    at Object.module.exports [as parse] (C:\wamp64\www\css-cleanup\node_modules\uncss\node_modules\css\node_modules\css-parse\index.js:485:10)
    at process (C:\wamp64\www\css-cleanup\node_modules\uncss\src\uncss.js:158:22)
    at tryCatcher (C:\wamp64\www\css-cleanup\node_modules\uncss\node_modules\bluebird\js\release\util.js:11:23)
    at Promise._settlePromiseFromHandler (C:\wamp64\www\css-cleanup\node_modules\uncss\node_modules\bluebird\js\release\promise.js:488:35)
    at Promise._settlePromise (C:\wamp64\www\css-cleanup\node_modules\uncss\node_modules\bluebird\js\release\promise.js:548:18)
    at Promise._settlePromise0 (C:\wamp64\www\css-cleanup\node_modules\uncss\node_modules\bluebird\js\release\promise.js:593:10)
    at Promise._settlePromises (C:\wamp64\www\css-cleanup\node_modules\uncss\node_modules\bluebird\js\release\promise.js:676:18)
```

I installed jsphantom, doesn't help. My Gulpfile looks like this:

```js
var gulp = require('gulp');
var uncss = require('gulp-uncss');


gulp.task('default', function () {
    return gulp.src('./css_new/app.css')
        .pipe(uncss({
            html: ['index.html']
        }))
        .pipe(gulp.dest('./css_new/'));
});
```

**Comment by RyanZim** [comment]
I think you have a syntax error in `app.css`. Perhaps a missing colon (`:`)?

Try running your complete css through w3's css validator: https://jigsaw.w3.org/css-validator/#validate_by_input.

If it turns out to be a syntax error, please close this.

**Comment by mikelambert** [comment]
Gulp-uncss appears to be using a versioned uncss, which uses css-parse, and
doesn't correctly handle nested selectorsnlike @media { @page { } }.

Using the version of uncss from github head should fix this. Maybe we
should request that gulp-uncss change their dependency? (Though changing it
yourself should fix it for you, in this case)

**Comment by RyanZim** [comment]
I knew gulp-uncss used css-parse, but I wasn't aware that it didn't handle nested selectors.

As far as changing the dependency, @nundel could also use https://github.com/postcss/gulp-postcss & https://github.com/RyanZim/postcss-uncss to avoid manually changing the dependency.

@mikelambert We really should push a release; have you tried emailing @giakki?

**Comment by mikelambert** [comment]
I emailed him yesterday to ask...

**Comment by nundel** [comment]
Also, guys, I'm working now with my bootsrap.min.css - trying to reduce it and I'm getting some not bad result, though some styles I need are gone. But also  I'm getting this 


[13:41:44] Starting 'default'...
ReferenceError: Can't find variable: insertionQ

  local:157
SECURITY_ERR: DOM Exception 18: An attempt was made to break through the security policy of the user agent.

  https://cdn.optimizely.com/js/2444890235.js:32 in ja
  https://cdn.optimizely.com/js/2444890235.js:32 in v
  https://cdn.optimizely.com/js/2444890235.js:134 in df
  https://cdn.optimizely.com/js/2444890235.js:217 in Ih
  https://cdn.optimizely.com/js/2444890235.js:234
  https://cdn.optimizely.com/js/2444890235.js:237
  https://cdn.optimizely.com/js/2444890235.js:240
ReferenceError: Can't find variable: insertionQ

  local:222
TypeError: 'undefined' is not a function (evaluating '$('.heroTrustIconsList').slick')

  local:220
  https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js:2
  https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js:2
  https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js:2
  https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js:2 in J
ReferenceError: Can't find variable: insertionQ

  local:221
ReferenceError: Can't find variable: SwitchToErrorPage

  local:64 in CheckCookiesSupported
  local:110
TypeError: 'undefined' is not an object (evaluating 'a.checkSessionState')

  https://apis.google.com/js/platform.js:45
  https://apis.google.com/js/platform.js:10
  https://apis.google.com/js/platform.js:4
  https://apis.google.com/js/platform.js:10
  https://apis.google.com/js/platform.js:10
  https://apis.google.com/js/platform.js:10
  https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.iw.FnS2zKMxWes.O/m=auth/exm=plusone/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCPc_WQBlL01d1dseky4LqAWbUD1dw/cb=gapi.loaded_1:174
SECURITY_ERR: DOM Exception 18: An attempt was made to break through the security policy of the user agent.

  http://static.olark.com/jsclient/loader0.js:1 in e
  http://static.olark.com/jsclient/loader0.js:1
  http://static.olark.com/jsclient/loader0.js:1
  http://static.olark.com/jsclient/loader0.js:1 in r
  http://static.olark.com/jsclient/loader0.js:1
  http://static.olark.com/jsclient/loader0.js:1
  http://static.olark.com/jsclient/loader0.js:1 in r
  http://static.olark.com/jsclient/loader0.js:1
  http://static.olark.com/jsclient/loader0.js:2
  http://static.olark.com/jsclient/loader0.js:1 in r
  http://static.olark.com/jsclient/loader0.js:1 in e
  http://static.olark.com/jsclient/loader0.js:2
  http://static.olark.com/jsclient/loader0.js:2
TypeError: 'undefined' is not an object (evaluating 'a.checkSessionState')

  https://apis.google.com/js/platform.js:45
  https://apis.google.com/js/platform.js:10
  https://apis.google.com/js/platform.js:4
  https://apis.google.com/js/platform.js:10
  https://apis.google.com/js/platform.js:10
  https://apis.google.com/js/platform.js:10
  https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.iw.FnS2zKMxWes.O/m=auth/exm=plusone/rt=j/sv=1/d=1/ed=1/am=AQ/rs=AGLTcCPc_WQBlL01d1dseky4LqAWbUD1dw/cb=gapi.loaded_1:174
TypeError: 'undefined' is not an object (evaluating 'a.checkSessionState')

  https://apis.google.com/js/platform.js:45
  https://apis.google.com/js/platform.js:11
  https://apis.google.com/js/platform.js:9
  https://apis.google.com/js/platform.js:46
  https://apis.google.com/js/platform.js:45
  https://apis.google.com/js/platform.js:1
TypeError: 'null' is not an object (evaluating 'iq(this).H')
    at https://s.ytimg.com/yts/jsbin/player-en_US-vflAbrXV8/base.js:7157
    at https://s.ytimg.com/yts/jsbin/player-en_US-vflAbrXV8/base.js:2172
    at https://s.ytimg.com/yts/jsbin/player-en_US-vflAbrXV8/base.js:4142
    at https://s.ytimg.com/yts/jsbin/player-en_US-vflAbrXV8/base.js:4229
    at https://s.ytimg.com/yts/jsbin/player-en_US-vflAbrXV8/base.js:7147
    at https://s.ytimg.com/yts/jsbin/www-embed-player-vfluPK2CM/www-embed-player.js:484
    at https://s.ytimg.com/yts/jsbin/www-embed-player-vfluPK2CM/www-embed-player.js:16
    at https://s.ytimg.com/yts/jsbin/www-embed-player-vfluPK2CM/www-embed-player.js:484
    at Th (https://s.ytimg.com/yts/jsbin/www-embed-player-vfluPK2CM/www-embed-player.js:482)
    at https://s.ytimg.com/yts/jsbin/www-embed-player-vfluPK2CM/www-embed-player.js:475
    at https://s.ytimg.com/yts/jsbin/www-embed-player-vfluPK2CM/www-embed-player.js:518

TypeError: 'undefined' is not an object (evaluating 'a.checkSessionState')

  https://apis.google.com/js/platform.js:45
  https://apis.google.com/js/platform.js:11
  https://apis.google.com/js/platform.js:9
  https://apis.google.com/js/platform.js:46
  https://apis.google.com/js/platform.js:45
  https://apis.google.com/js/platform.js:1
[13:41:49] Finished 'default' after 4.86 s

SO I just wonder are these error sufficient or my uncss works well?
Thnx

**Comment by RyanZim** [comment]
@nundel It looks like there are a couple of different things going on here.

---

> ReferenceError: Can't find variable: insertionQ

I'm not sure where that's coming from. Do you have/use a variable named `insertionQ` in your gulpfile or JS?

---

> SECURITY_ERR: DOM Exception 18: An attempt was made to break through the security policy of the user agent.

This seems to be some sort of a CORS error. Are you using `<canvas>` on your page? See http://timdietrich.me/blog/dom-exception-18-security-error/. Try opening index.html in a webkit-based browser and see if it reports an error in the console.

---

> TypeError: 'undefined' is not a function (evaluating '$('.heroTrustIconsList').slick')

It seems you've encountered the mysterious bug https://github.com/giakki/uncss/issues/220. It has also been reported at #232. @XhmikosR said there:

> ...In my case moving all JS to external files fixed the errors.

It is believed that this error does not affect the css output; of course, we can't be 100% sure.

---

Regarding bootstrap:

> I'm getting some not bad result, though some styles I need are gone.

You can try using https://github.com/giakki/uncss/wiki/Using-uncss-with-Bootstrap. As noted there, this will make your css a little bigger, but should get it working (unless you are adding content with JS).

**Comment by RyanZim** [comment]
@nundel v0.14.0 has been released: https://github.com/giakki/uncss/releases/tag/0.14.0.

Please close this. Thanks!

**Comment by nundel** [comment]
hey guys, still errror: 
module.js:327
    throw err;
    ^

Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\wamp64\www\css-cleanup\node_modules\gulp-uncss\node_modules\uncss\src\uncss.js:4:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\wamp64\www\css-cleanup\node_modules\gulp-uncss\index.js:3:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

**Comment by nundel** [comment]
done. also this Error: Cannot find module 'postcss'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\wamp64\www\css-cleanup\node_modules\gulp-uncss\node_modules\uncss\src\uncss.js:11:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\wamp64\www\css-cleanup\node_modules\gulp-uncss\index.js:3:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

**Comment by mikelambert** [comment]
My fix should fix the `async` issue. I am not sure what is up with the `postcss` issue. How are you installing/including this module in your project? Are you using `npm install`, and if so with what command? What does your project's `package.json` look like?

**Comment by nundel** [comment]
I am using npm install. 
That's how package.json looks
{
  "name": "yes",
  "version": "1.0.0",
  "description": "Get your contracts reviewed at a fraction of the cost",
  "devDependencies": {
    "grunt": "^1.0.1",
    "gulp": "^3.9.0",
    "gulp-clean-css": "^2.0.10",
    "gulp-compass": "^2.1.0",
    "gulp-install": "^0.6.0",
    "gulp-livereload": "^3.8.1",
    "gulp-postcss": "^6.1.1",
    "gulp-purifycss": "^0.2.0",
    "gulp-sass": "^2.3.2",
    "gulp-uncss": "^1.0.5"
  },
  "main": "Gulpfile.js",
  "dependencies": {
    "compass": "^0.1.1",
    "css": "^2.2.1",
    "gulp": "^3.9.1",
    "gulp-clean-css": "^2.0.10",
    "gulp-compass": "^2.1.0",
    "gulp-concat": "^2.6.0",
    "gulp-concat-util": "^0.5.5",
    "gulp-livereload": "^3.8.1",
    "gulp-purifycss": "^0.2.0",
    "gulp-sass": "^2.3.2",
    "gulp-uncss": "^1.0.5",
    "node": "^0.0.0",
    "postcss-use": "^2.2.0",
    "purify-css": "^1.1.9",
    "uncss": "^0.13.0"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}

**Comment by RyanZim** [comment]
@nundel gulp-uncss has not yet updated to the latest version of uncss.

**Comment by mikelambert** [comment]
@RyanZim, I'm not sure that's true? gulp-uncss uses: "uncss": "^0.13.0", which should pull in the latest version of uncss on install.

**Comment by RyanZim** [comment]
> gulp-uncss uses: "uncss": "^0.13.0", which should pull in the latest version of uncss on install.

@mikelambert Not during pre-v1.0.0. https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

**Comment by nundel** [comment]
@mikelambert I am using "0.14.0" version

**Comment by nundel** [comment]
still getting Error: Cannot find module 'postcss'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\wamp64\www\css-cleanup\node_modules\uncss\src\uncss.js:11:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\wamp64\www\css-cleanup\node_modules\gulp-uncss\index.js:3:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

**Comment by RyanZim** [comment]
Perhaps it would be best to try to make a reduced test case (remove everything that isn't relevant to the issue). If you don't uncover the issue in the process, you could post it as a repo on GH so that we can debug using your exact code.

**Comment by RyanZim** [comment]
@nundel How's that test case working?

**Comment by RyanZim** [comment]
@mikelambert It looks like this has been resolved or abandoned, can you close?
