### ISSUE TITLE
Fontconfig warning: ignoring C.UTF-8: not a valid language tag

### ISSUE THREAD

**Issue by supersonicBlonde** [giakki/uncss#267]
Hello ...

I have this issue when i run the following 
`
uncss --htmlroot _site _site/**/**/*.html | cssnano > css/s.min.css
`
```
Fontconfig warning: ignoring C.UTF-8: not a valid language tag
/home/ubuntu/workspace/static/node_modules/uncss/node_modules/bluebird/js/release/async.js:48
        fn = function () { throw arg; };
                           ^

Error: Fontconfig warning: ignoring C.UTF-8: not a valid language tag

    at Socket.onStderr (/home/ubuntu/workspace/static/node_modules/uncss/node_modules/phridge/lib/spawn.js:93:28)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:536:20)
```

**Comment by RyanZim** [comment]
This looks like a dupe of https://github.com/giakki/uncss/issues/166. If that works for you, please close this. Thanks!

**Comment by supersonicBlonde** [comment]
Yes. perfect. Thanks :)
