### ISSUE TITLE
"Error: UnCSS: no stylesheets found"

### ISSUE THREAD

**Issue by 7s3** [giakki/uncss#290]
I've come across this error and I'm not sure how to solve it. This CSS file is not minified or cached on Cloudflare.

```
C:\Users\1q2w3e>uncss http://example.com/css/style.css > test123.css
C:\Users\1q2w3e\AppData\Roaming\npm\node_modules\uncss\node_modules\bluebird\js\release\async.js:48
        fn = function () { throw arg; };
                           ^

Error: UnCSS: no stylesheets found
    at processWithTextApi (C:\Users\1q2w3e\AppData\Roaming\npm\node_modules\uncss\src\uncss.js:146:15)
    at tryCatcher (C:\Users\1q2w3e\AppData\Roaming\npm\node_modules\uncss\node_modules\bluebird\js\release\util.js:11:23)    at Promise._settlePromiseFromHandler (C:\Users\1q2w3e\AppData\Roaming\npm\node_modules\uncss\node_modules\bluebird\js\release\promise.js:488:35)
    at Promise._settlePromise (C:\Users\1q2w3e\AppData\Roaming\npm\node_modules\uncss\node_modules\bluebird\js\release\promise.js:548:18)
    at Promise._settlePromise0 (C:\Users\1q2w3e\AppData\Roaming\npm\node_modules\uncss\node_modules\bluebird\js\release\promise.js:593:10)
    at Promise._settlePromises (C:\Users\1q2w3e\AppData\Roaming\npm\node_modules\uncss\node_modules\bluebird\js\release\promise.js:676:18)
    at Promise._fulfill (C:\Users\1q2w3e\AppData\Roaming\npm\node_modules\uncss\node_modules\bluebird\js\release\promise.js:617:18)
    at PromiseArray._resolve (C:\Users\1q2w3e\AppData\Roaming\npm\node_modules\uncss\node_modules\bluebird\js\release\promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (C:\Users\1q2w3e\AppData\Roaming\npm\node_modules\uncss\node_modules\bluebird\js\release\promise_array.js:143:14)
    at Promise._settlePromise (C:\Users\1q2w3e\AppData\Roaming\npm\node_modules\uncss\node_modules\bluebird\js\release\promise.js:553:26)
    at Promise._settlePromise0 (C:\Users\1q2w3e\AppData\Roaming\npm\node_modules\uncss\node_modules\bluebird\js\release\promise.js:593:10)
    at Promise._settlePromises (C:\Users\1q2w3e\AppData\Roaming\npm\node_modules\uncss\node_modules\bluebird\js\release\promise.js:676:18)
    at Async._drainQueue (C:\Users\1q2w3e\AppData\Roaming\npm\node_modules\uncss\node_modules\bluebird\js\release\async.js:125:16)
    at Async._drainQueues (C:\Users\1q2w3e\AppData\Roaming\npm\node_modules\uncss\node_modules\bluebird\js\release\async.js:135:10)
    at Immediate.Async.drainQueues (C:\Users\1q2w3e\AppData\Roaming\npm\node_modules\uncss\node_modules\bluebird\js\release\async.js:16:14)
    at runCallback (timers.js:649:20)
```

**Comment by RyanZim** [comment]
You need to pass `uncss` the URL to the actual site (i.e. the HTML), not just the CSS.

Example:

    uncss http://example.com/ > test123.css

Please close this issue. Thanks!

**Comment by 7s3** [comment]
Ughh...I'm dumb. I can't believe I just did that :)
Funny thing is I never had a problem, stopped using uncss for a while and forgot the correct command.
Thanks for the quick reply!
