### ISSUE TITLE
Error while run inside docker

### ISSUE THREAD

**Issue by ganlanyuan** [giakki/uncss#308]
Hi, 
I got the following error running `gulp-uncss` in docker
```
/www/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory

/www/node_modules/uncss/node_modules/bluebird/js/release/async.js:48
        fn = function () { throw arg; };
                           ^
Error: /www/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory

    at Socket.onStderr (/www/node_modules/phridge/lib/spawn.js:93:28)
    at emitOne (events.js:120:20)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at Pipe.onread (net.js:588:20)
```
while there is no error when run it locally.

gulpfile.js
```javascript
function doAmpUncss(src, dest, options) {
  return gulp.src(src)
    .pipe($.uncss(options))
    .pipe($.rename('amp.css'))
    .pipe(gulp.dest(dest));
}

gulp.task('build:ampUncss', () => {
  doAmpUncss(cssDest + '/main.final.css', cssDest, {
      html: ['amp-article.html'],
      ignore: ['#sidebar', '#sidebar>ul>li>a', '.hasImgs li amp-img', '.hidden-svg'],
  });
});
```

Could you help me find out what's going wrong?

**Comment by RyanZim** [comment]
Dupe of https://github.com/giakki/uncss/issues/165; see there for solution.

**Comment by ganlanyuan** [comment]
Thanks @RyanZim , this solved my problem!
