### ISSUE TITLE
Error when running: "No stylesheets found"

### ISSUE THREAD

**Issue by JayHoltslander** [giakki/uncss#334]
Ran the example CLI code shown in the [readme](https://github.com/giakki/uncss). Get this error.

Can you shed any light?

````bash
uncss http://getbootstrap.com/examples/jumbotron/ > ~/Desktop/uncss-stylesheet.css

/usr/local/lib/node_modules/uncss/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

Error: UnCSS: no stylesheets found
    at processWithTextApi (/usr/local/lib/node_modules/uncss/src/uncss.js:134:15)
    at tryCatcher (/usr/local/lib/node_modules/uncss/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/uncss/node_modules/bluebird/js/release/promise.js:509:35)
    at Promise._settlePromise (/usr/local/lib/node_modules/uncss/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/uncss/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/uncss/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/local/lib/node_modules/uncss/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/usr/local/lib/node_modules/uncss/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/usr/local/lib/node_modules/uncss/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/usr/local/lib/node_modules/uncss/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/uncss/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/uncss/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/local/lib/node_modules/uncss/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/uncss/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/uncss/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
````

**Comment by RyanZim** [comment]
getbootstrap.com changed their site around; that page is now a redirect to https://getbootstrap.com/docs/3.3/examples/jumbotron/. uncss doesn't follow the redirect, so it doesn't work correctly. We need to update the docs to use an up-to date link; care to submit a PR?
