### ISSUE TITLE
Error on self-signed certificates when a request to a local server with TLS (SSL) and self-signed certificate is issued.

### ISSUE THREAD

**Issue by RyoIkarashi** [giakki/uncss#359]
Hi, I'm using latest `uncss` and ran `uncss https://sample.dev > /path/to/stylesheet.css` to remove unused styles from my local server with HTTPS and self signed certificates.
but I got an TLS-related error.

Node version: v9.4.0

```
UnhandledPromiseRejectionWarning: Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1041:34)
    at TLSSocket.emit (events.js:160:13)
    at TLSSocket._finishInit (_tls_wrap.js:638:8)
(node:34329) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:34329) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I think an option for self-signed certificate should be provided or ignoring TLS related errors should be applied with something like these options in [src/utility.js at Line 112-113](https://github.com/giakki/uncss/blob/master/src/utility.js#L112-L113) when a request is issued.

```
request({
  url: filename,
  headers: { 'User-Agent': 'UnCSS' },
  // ignore TLS related errors
  rejectUnauthorized: false,
  strictSSL: false,
  // OR just specify self-signed cert and key
  agentOptions: {
    cert: fs.readFileSync("/path/to/cert.crt")
    key: fs.readFileSync("/path/to/key.key")
  }
}, callback);
```

@giakki What do you think about this?

**Comment by RyoIkarashi** [comment]
Any thoughts or workarounds on this?

**Comment by RyanZim** [comment]
Your patch might work; I'm not the expert on this. @mikelambert @XhmikosR thoughts?

**Comment by mikelambert** [comment]
I think I'm okay with uncss ignoring SSL/TLS errors.

I'm not able to imagine any security holes (to the local machine, or to the resulting-site that uses the uncss'ed CSS) that could happen as a result of this.

But given those are probably "famous last words", maybe put the ignoring behind a flag, just to be safe?

**Comment by RyanZim** [comment]
SGTM, PR welcome.

**Comment by josh-g3** [comment]
Ran into the same thing writing a Chai integration test. If this is running somewhere you don't care about TLS verification, the line `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0"` anywhere prior to sending the request seems to do the trick.

**Comment by reddysridhar53** [comment]
Is this issue still open?

**Comment by nvioli** [comment]
I'm having a related issue, though it looks like @RyoIkarashi's solution (and perhaps their problem) is around insecurely requesting the stylesheets.

Rather, I'm having a problem in `jsdom` when trying to request the html with an invalid certificate. The solution to my problem is to allow passing `strictSSL` option to `jsdom`. See my PR, and please let me know if my issue is different than this one and should be discussed separately.
