### ISSUE TITLE
TypeError: Bad argument thrown on Windows

### ISSUE THREAD

**Issue by ben-eb** [giakki/uncss#75]
Migrate from https://github.com/ben-eb/gulp-uncss/issues/9

Stack trace:

``` bash
child_process.js:933
  var r = this._handle.spawn(options);
                       ^
TypeError: Bad argument
    at ChildProcess.spawn (child_process.js:933:24)
    at exports.spawn (child_process.js:733:9)
    at spawnPhantom (c:\_dev\_labs\sp-build-with-server\node_modules\gulp-uncss\node_modules\uncss\node_modules\node-phantom-simple\node-phantom-simple.js:70:23)
    at Object.exports.create (c:\_dev\_labs\sp-build-with-server\node_modules\gulp-uncss\node_modules\uncss\node_modules\node-phantom-simple\node-phantom-simple.js:201:5)
    at c:\_dev\_labs\sp-build-with-server\node_modules\gulp-uncss\node_modules\uncss\lib\phantom.js:37:21
    at Object.async.whilst (c:\_dev\_labs\sp-build-with-server\node_modules\gulp-uncss\node_modules\uncss\node_modules\async\lib\async.js:663:13)
    at init (c:\_dev\_labs\sp-build-with-server\node_modules\gulp-uncss\node_modules\uncss\lib\phantom.js:34:18)
    at fn (c:\_dev\_labs\sp-build-with-server\node_modules\gulp-uncss\node_modules\uncss\node_modules\async\lib\async.js:626:34)
    at Object._onImmediate (c:\_dev\_labs\sp-build-with-server\node_modules\gulp-uncss\node_modules\uncss\node_modules\async\lib\async.js:542:34)
    at processImmediate [as _immediateCallback] (timers.js:336:15)
```

**Comment by gsklee** [comment]
@giakki This error shows up again when using io.js (v1.0.4).

**Comment by OleVik** [comment]
In regards to the just referenced issue, I am running `gulp-uncss@1.0.5` locally in conjunction with `uncss@0.13.0` globally, and get seemingly the same error as @ben-eb had back in June of 2014. See the downstream issue for a stack trace. Has anyone found a solution to it?

Unfortunately I do not know how to debug from the trace, but as the error occurs on a fresh local installation of the project I suspect it has something to do with an uninstalled package that was dropped from my package.json.

**Comment by mikelambert** [comment]
This appears to be due to a half-completed installation of phantomjs-prebuilt, see this other issue for more info: https://github.com/Medium/phantomjs/issues/533

In my case, following these instructions fixed it for me:
```
$ cd node_modules/phantomjs-prebuilt
$ node install.js
```
