### ISSUE TITLE
UnCSS fails on localhost connections with `Error: Status not 200`.

### ISSUE THREAD

**Issue by karanlyons** [giakki/uncss#83]
```console
$ uncss http://localhost:5757/index.html
Error: Status not 200
    at Request.<anonymous> (/usr/local/lib/node_modules/uncss/lib/lib.js:77:58)
    at Request.emit (events.js:95:17)
    at Request.onResponse (/usr/local/lib/node_modules/uncss/node_modules/request/request.js:924:10)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socketOnData [as ondata] (http.js:1583:20)
    at TCP.onread (net.js:527:27)
```

```console
$ node
var request = require('/usr/local/lib/node_modules/uncss/node_modules/request');
request({
  uri: "http://localhost:5757/index.html",
}, function(error, response, body) {
  console.log(response.statusCode);
});
200
```

Not sure what the cause of the discrepancy is here. Altering the port, the FQDN, or the path to the page doesn't change the result from either UnCSS or request. It's still entirely possible that the problem is me.

**Comment by tannerhodges** [comment]
Nope, thanks!

Not sure what I was doing before - seems silly now. I just reinstalled and tried with a Mixture project: `uncss http://localhost:7774/ > styles.css` worked like a charm.

Definitely going to be using this a lot now. Thanks again, really appreciate it.
